In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from scipy.stats import multivariate_normal
import numpy as np
import torch
from torch import nn, Tensor

from multi_head_dnn import DNN, Trainer

In [3]:
N = 5
M = 3


In [4]:
mu = np.random.random(M)
sigma = (np.random.randn(int((M*(M+1))/2)))
cov = np.zeros((M, M))
cov[np.tril_indices(M)] = sigma
cov.T[np.tril_indices(M)] = sigma
cov += 2*np.eye(M)
mu, cov

(array([0.74127396, 0.51501439, 0.45983416]),
 array([[ 2.38002323, -1.83590423,  0.75663054],
        [-1.83590423,  2.67255884,  0.54707812],
        [ 0.75663054,  0.54707812,  3.25593852]]))

In [5]:
norm = multivariate_normal(mu, cov)

In [6]:
X = Tensor(norm.rvs(N))
if N == 1:
    X = X.unsqueeze(dim=0)
X.shape

torch.Size([5, 3])

In [7]:
model = DNN(
    input_dims = M,
    hidden_dims = 10,
)

In [8]:
model(X)

tensor([-15.8170,  -6.3859,  -4.8589,  -4.6084,  -4.7957],
       grad_fn=<SubBackward0>)

In [9]:
Y = Tensor(np.log(norm.pdf(X)))

In [10]:
trainer = Trainer(model, 10000)

In [11]:
trainer.train(X, Y)

In [12]:
trainer.predict(X)

tensor([-5.7350, -4.5776, -4.2807, -3.9015, -4.1598], grad_fn=<SubBackward0>)

In [13]:
Y

tensor([-5.7350, -4.5776, -4.2807, -3.9015, -4.1598])